# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "плохая калибровка руля направления"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "плохая калибровка серво руля направления"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "сервопривод руля направления отказал"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot не удалось импортировать необходимые модули. Вы забыли запустить "
"sudo python3 setup.py install?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ВНИМАНИЕ: ошибка библиотеки python ujson, синтаксический анализ будет "
"потреблять больше процессора"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "сервокалибровка недействительна"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "не удалось открыть сервопривод:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "не удалось установить неблокирующий / эксклюзивный"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "нашел"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "загрузка серво калибровки"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "ВНИМАНИЕ: использование сервокалибровки по умолчанию !!"

#: ../servo.py:756
msgid "probing"
msgstr "зондирование"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "сервопривод Arduino обнаружен"

#: ../servo.py:781
msgid "device needed for option"
msgstr "устройство, необходимое для опции"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea не удалось разобрать gps"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea не смог разобрать ветер"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "парсинг исключений apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "разбор исключений vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "необработанная колонна труб nmea"

#: ../nmea.py:405
msgid "lost serial"
msgstr "потерянный сериал"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea получил флаг для технологической трубы:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "к нему обращается другой процесс?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "истекло время ожидания последовательного устройства"

#: ../nmea.py:521
msgid "failed to open"
msgstr "не удалось открыть"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "сервер nmea на порту"

#: ../nmea.py:587
msgid "bind failed."
msgstr "привязка не удалась."

#: ../nmea.py:589
msgid "listening on port"
msgstr "прослушивание порта"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "для соединений nmea"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "Сервер nmea имеет слишком много подключений"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "клиент nmea потерял соединение"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "nmea sock не в розетки!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea не удалось отменить регистрацию сокета"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea не удалось удалить fd"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea не удалось удалить адрес"

#: ../nmea.py:737
msgid "invalid value"
msgstr "Неверное значение"

#: ../nmea.py:747
msgid "connect error"
msgstr "ошибка подключения"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "не удалось подключиться"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "клиент nmea подключен"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "опрос занял слишком много времени в процессе nmea!"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "мост nmea потерял соединение с сервером"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "Мост Nmea потерял трубу из-за автопилота"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "флаг необработанного голосования nmea bridge"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "Цикл процесса nmea слишком медленный:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "ошибка блока трубы на recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "не удалось восстановить неблокирующую трубу!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "труба полная"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "не могу отправить"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "не удалось декодировать сокет данных!"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "не удалось закодировать сокет данных!"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "не удалось написать"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "ОШИБКА нет соединений в часах"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "удалить повторяющееся соединение udp"

#: ../server.py:486
msgid "failed to monitor "
msgstr "не удалось отследить"

#: ../server.py:490
msgid "creating config directory: "
msgstr "создание каталога конфигурации:"

#: ../server.py:497
msgid "failed to load"
msgstr "ошибка загрузки"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "данные резервного копирования также не удалось"

#: ../server.py:570
msgid "failed to write"
msgstr "не удалось написать"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: сбой привязки; уже запущен сервер?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "постоянный магазин занял слишком много времени!"

#: ../server.py:706
msgid "max connections reached"
msgstr "достигнуто максимальное количество подключений"

#: ../server.py:709
msgid "server add socket"
msgstr "сервер добавить сокет"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "внутренняя труба закрыта, сервер выходит"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "серверный сокет закрыт из-за промывки !!"

#: ../signalk.py:52
msgid "service removed"
msgstr "служба удалена"

#: ../signalk.py:55
msgid "server lost"
msgstr "сервер потерян"

#: ../signalk.py:61
msgid "service add"
msgstr "добавление услуги"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "не удалось"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "автоматическое обнаружение невозможно"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "пытаться"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "или же"

#: ../signalk.py:138
msgid "read token"
msgstr "читать токен"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "не удалось прочитать токен"

#: ../signalk.py:171
msgid "probe"
msgstr "зонд"

#: ../signalk.py:175
msgid "could not"
msgstr "не мог"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "не удалось получить / проанализировать данные из"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "посмотреть, готов ли токен"

#: ../signalk.py:207
msgid "received token"
msgstr "получил токен"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "не удалось сохранить токен"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "ошибка при запросе доступа"

#: ../signalk.py:236
msgid "request access url"
msgstr "запросить URL-адрес доступа"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "не может создать соединение:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "плохой статус, отклонение токена"

#: ../signalk.py:264
msgid "connection refused"
msgstr "В соединении отказано"

#: ../signalk.py:313
msgid "server found"
msgstr "найден сервер"

#: ../signalk.py:334
msgid "connected to"
msgstr "подключен к"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Исключение преобразования сигнала-> pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "получили"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "не удалось отправить обновления"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "не удалось разобрать сообщение:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "датчик найден"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "неизвестные данные проанализированы!"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"не удалось загрузить научную библиотеку, невозможно выполнить обновление "
"калибровки!"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Плохая калибровка акселерометра"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "магнитные искажения"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Ошибка загрузки"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "не удалось загрузить пилот"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Доступные пилоты"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "предупреждение: не удалось открыть специальный файл"

#: ../autopilot.py:157
msgid "for writing"
msgstr "для записи"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "не могу погладить сторожевого пса"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"предупреждение: не удалось сделать процесс автопилота в реальном времени"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "сервер / клиент работает слишком медленно_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "датчики работают слишком медленно"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "программа автопилота работает слишком медленно"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "сервопривод работает слишком медленно"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "итерация автопилота работает слишком медленно"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "ВНИМАНИЕ: запуск автопилота от имени пользователя root!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "инициализация завершена"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Библиотека RTIMU не обнаружена, установите ее"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Использование файла настроек"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "ОШИБКА: IMU не обнаружен"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "ОШИБКА: сбой инициализации IMU, инерционные данные недоступны"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr ""
"предупреждение, не удалось заставить imu обрабатывать в реальном времени"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "сделал imu процесс в реальном времени"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "установка начального смещения гироскопа"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "IMU процесс не успел вовремя"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "не удалось прочитать ИДУ!"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "imu rate установлен на рейтинг"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "слишком высокое смещение гироскопа, сброс датчиков"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "компас вне диапазона, сброс"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "предупреждение, не удалось выполнить другой процесс калибровки"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"предупреждение, не удалось остановить процесс калибровки, пытаюсь "
"восстановить"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "предупреждение, не удалось изменить процесс калибровки"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "калибровка загружена, запуск"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "неудачная импортная калибровка"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "значения ускорения недопустимы"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "переполнение в сокете pypilot udp"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "переполнение в сокете pypilot"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "не удалось отправить пакет UDP"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "сокету pypilot не удалось отправить"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "отправка сокета заняла слишком много времени!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "ошибка отправки сокета"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "исключение сокета pypilot"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "возврат к неблокирующему сокету python потребляет больше процессора"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "ошибка отправки сокета при сбросе сервера"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "ошибка при получении данных"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "чтение ошибок"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "нашел больше устройств по пути"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "удаление устройства GPS"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "нет модуля пюдев! будет часто сканировать USB-устройства!"

#: ../serialprobe.py:359
msgid "success"
msgstr "успех"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "не удалось записать устройство"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "предупреждение, регистрация существующего значения:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "не удалось прочитать файл конфигурации:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "не удалось записать файл конфигурации:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Исключение записи конфигурационного файла:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "автоматическое определение сервера pypilot невозможно"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "неверное сообщение от сервера:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "предупреждение, у клиента pypilot уже есть соединение"

#: ../client.py:363
msgid "connect failed to"
msgstr "не удалось подключиться к"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "не удалось подключиться к"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "сервер pypilot не найден"

#: ../client.py:522
msgid "usage"
msgstr "Применение"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "установить хост или IP-адрес"

#: ../client.py:526
msgid "print info about each value type"
msgstr "распечатать информацию о каждом типе значения"

#: ../client.py:527
msgid "continuous watch"
msgstr "непрерывное наблюдение"

#: ../client.py:528
msgid "show this message"
msgstr "показать это сообщение"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "не удалось получить список значений!"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "получение тайм-аута"

#: ../client.py:569
msgid "missing"
msgstr "отсутствующий"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "неверное начальное значение для свойства диапазона"

#: ../values.py:184
msgid "invalid set"
msgstr "неверный набор"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "gpsd подключен"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd не удалось подключиться"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "исключение при подключении к gps"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd отключен"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "gpsd PROBE успех"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "зонд gpsd отказал"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd деактивирован"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr ""
"gpsd не удалось определить последовательную скорость передачи данных "
"устройства"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "gpsd тайм-аут из-за отсутствия данных"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd получил недопустимое сообщение"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd получил флаг для трубы:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "gpsd серийный зонд"

#~ msgid "exception in calibration:"
#~ msgstr "исключение при калибровке:"

#~ msgid "warning: unhandled message"
#~ msgstr "предупреждение: необработанное сообщение"

#~ msgid "Autopilot Control"
#~ msgstr "Управление автопилотом"

#~ msgid "AP"
#~ msgstr "Ты"

#~ msgid "N/A"
#~ msgstr "N / A"

#~ msgid "        N/A        "
#~ msgstr "N / A"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "N / A"

#~ msgid "port"
#~ msgstr "порт"

#~ msgid "starboard"
#~ msgstr "правый борт"

#~ msgid "Pilot"
#~ msgstr "Пилот"

#~ msgid "Compass"
#~ msgstr "Компас"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Ветер"

#~ msgid "True Wind"
#~ msgstr "Настоящий ветер"

#~ msgid "Center"
#~ msgstr "Центр"

#~ msgid "&Scope"
#~ msgstr "&Сфера"

#~ msgid "&Client"
#~ msgstr "&Клиент"

#~ msgid "C&alibration"
#~ msgstr "к&алибровка"

#~ msgid "Close"
#~ msgstr "Закрывать"

#~ msgid "Calibration"
#~ msgstr "Калибровка"

#~ msgid "Boat is level"
#~ msgstr "Лодка ровная"

#~ msgid "Reset"
#~ msgstr "Сброс настроек"

#~ msgid "Alignment"
#~ msgstr "Выравнивание"

#~ msgid "Heading"
#~ msgstr "Заголовок"

#~ msgid "     N/A     "
#~ msgstr "N / A"

#~ msgid "Offset"
#~ msgstr "Компенсировать"

#~ msgid "Coords"
#~ msgstr "Координаты"

#~ msgid "Sea"
#~ msgstr "Море"

#~ msgid "Boat"
#~ msgstr "Лодка"

#~ msgid "Scope"
#~ msgstr "Сфера"

#~ msgid "Pitch"
#~ msgstr "Подача"

#~ msgid "Roll"
#~ msgstr "Рулон"

#~ msgid "Heel"
#~ msgstr "Каблук"

#~ msgid "alignment"
#~ msgstr "выравнивание"

#~ msgid "Calibration Age"
#~ msgstr "Возраст калибровки"

#~ msgid "Clear"
#~ msgstr "ясно"

#~ msgid "calibration locked"
#~ msgstr "калибровка заблокирована"

#~ msgid "accel"
#~ msgstr "ускорение"

#~ msgid "Sigma Points"
#~ msgstr "Sigma Points"

#~ msgid "local history"
#~ msgstr "местная история"

#~ msgid "current"
#~ msgstr "Текущий"

#~ msgid "Calibration Points"
#~ msgstr "Точки калибровки"

#~ msgid "compass"
#~ msgstr "компас"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Нажмите каждую кнопку, когда руль направления находится в правильном "
#~ "положении для калибровки."

#~ msgid "Rudder"
#~ msgstr "Руль"

#~ msgid "Reset Calibration"
#~ msgstr "Сбросить калибровку"

#~ msgid "Rudder Is Centered"
#~ msgstr "Руль по центру"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "Руль направления правого борта"

#~ msgid "Scale"
#~ msgstr "Шкала"

#~ msgid "Rudder is Port Range"
#~ msgstr "Руль - диапазон порта"

#~ msgid "Non Linearity"
#~ msgstr "Нелинейность"

#~ msgid " range +-"
#~ msgstr "диапазон + -"

#~ msgid "degrees"
#~ msgstr "градусы"

#~ msgid "rudder"
#~ msgstr "руль"

#~ msgid "settings"
#~ msgstr "настройки"

#~ msgid "failed to load pywavefront:"
#~ msgstr "не удалось загрузить pywavefront:"

#~ msgid "invalid display dimensions"
#~ msgstr "неверные размеры дисплея"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Вы добавили репозиторий pypilot_data?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "не найден, текстурный компас использовать нельзя"

#~ msgid "Refresh"
#~ msgstr "Обновить"

#~ msgid "Connected"
#~ msgstr "Связанный"

#~ msgid "Disconnected"
#~ msgstr "Отключен"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "предупреждение, указано недопустимое значение выбора"

#~ msgid "pypilot Scope"
#~ msgstr "область действия pypilot"

#~ msgid "Zero"
#~ msgstr "Нуль"

#~ msgid "Scale +"
#~ msgstr "Масштаб +"

#~ msgid "Scale -"
#~ msgstr "Шкала -"

#~ msgid "Offset /\\"
#~ msgstr "Компенсировать /\\"

#~ msgid "Offset \\/"
#~ msgstr "Компенсировать \\/"

#~ msgid "Freeze"
#~ msgstr "Заморозить"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Время"

#~ msgid "values not found:"
#~ msgstr "значения не найдены:"

#~ msgid "in"
#~ msgstr "в"

#~ msgid "seconds"
#~ msgstr "секунды"

#~ msgid "nmea client failed to connect to"
#~ msgstr "клиенту nmea не удалось подключиться к"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "не удалось создать сокет nmea как хост: порт"

#~ msgid "terminate calibration process"
#~ msgstr "прекратить процесс калибровки"
