# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.32\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "calibração ruim do leme"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "calibração ruim do servo leme"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "servo leme autogain falhou"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"O pypilot falhou ao importar os módulos necessários. Você se esqueceu de "
"executar sudo python3 setup.py install?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr "AVISO: a biblioteca python ujson falhou, a análise consumirá mais cpu"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "calibração do servo inválida"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "falhou ao abrir servo em:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "falhou definir não bloqueante / exclusivo"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "encontrado"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "carregando calibração servo"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "AVISO: usando a calibração do servo padrão !!"

#: ../servo.py:756
msgid "probing"
msgstr "sondagem"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "servo arduino detectado"

#: ../servo.py:781
msgid "device needed for option"
msgstr "dispositivo necessário para a opção"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea falhou ao analisar gps"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea falhou ao analisar o vento"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "exceção de análise de apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "análise de exceção vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "sem manuseio nmea string pipe"

#: ../nmea.py:405
msgid "lost serial"
msgstr "série perdida"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea obteve sinalizador para tubo de processo:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "outro processo está acessando isso?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "dispositivo serial expirou"

#: ../nmea.py:521
msgid "failed to open"
msgstr "falhou para abrir"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "servidor nmea na porta"

#: ../nmea.py:587
msgid "bind failed."
msgstr "ligação falhou."

#: ../nmea.py:589
msgid "listening on port"
msgstr "ouvindo na porta"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "para conexões nmea"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "O servidor nmea tem muitas conexões"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "nmea cliente perdeu a conexão"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "meia nmea não em soquetes!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea falhou ao cancelar o registro do soquete"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea falhou ao remover fd"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea falhou ao remover o endereço"

#: ../nmea.py:737
msgid "invalid value"
msgstr "Valor inválido"

#: ../nmea.py:747
msgid "connect error"
msgstr "erro de conexão"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "Falhou ao conectar"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "nmea cliente conectado"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "enquete demorou muito no processo nmea!"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "nmea bridge perdeu a conexão do servidor"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea ponte perdeu tubo para piloto automático"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "sinalizador de enquete não tratada de ponte nmea"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "nmea loop de processo muito lento:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "bloco de tubos de erro no recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "falhou ao receber o tubo não bloqueante!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "cano cheio"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "Não é possível enviar"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "falhou ao decodificar o soquete de dados!"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "falhou ao codificar o soquete de dados!"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "falha na escrita"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "ERROR sem conexões no relógio"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "remover conexão udp duplicada"

#: ../server.py:486
msgid "failed to monitor "
msgstr "falha ao monitorar"

#: ../server.py:490
msgid "creating config directory: "
msgstr "criando diretório de configuração:"

#: ../server.py:497
msgid "failed to load"
msgstr "Falha ao carregar"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "dados de backup também falharam"

#: ../server.py:570
msgid "failed to write"
msgstr "falhou em escrever"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: ligação falhou; já está rodando um servidor?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "o armazenamento persistente demorou muito!"

#: ../server.py:706
msgid "max connections reached"
msgstr "conexões máximas alcançadas"

#: ../server.py:709
msgid "server add socket"
msgstr "servidor adicionar soquete"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "tubo interno fechado, servidor saindo"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "Soquete do servidor fechado do flush !!"

#: ../signalk.py:52
msgid "service removed"
msgstr "serviço removido"

#: ../signalk.py:55
msgid "server lost"
msgstr "servidor perdido"

#: ../signalk.py:61
msgid "service add"
msgstr "adicionar serviço"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "falhei em"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "autodetecção não é possível"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "Experimente"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "ou"

#: ../signalk.py:138
msgid "read token"
msgstr "ler token"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "falhou ao ler o token"

#: ../signalk.py:171
msgid "probe"
msgstr "sonda"

#: ../signalk.py:175
msgid "could not"
msgstr "não conseguia"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "falha ao recuperar / analisar dados de"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "veja se o token está pronto"

#: ../signalk.py:207
msgid "received token"
msgstr "token recebido"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "falha ao armazenar token"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "erro ao solicitar acesso"

#: ../signalk.py:236
msgid "request access url"
msgstr "solicitar url de acesso"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "não pode criar conexão:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "status ruim, rejeitando token"

#: ../signalk.py:264
msgid "connection refused"
msgstr "Ligação recusada"

#: ../signalk.py:313
msgid "server found"
msgstr "servidor encontrado"

#: ../signalk.py:334
msgid "connected to"
msgstr "conectado a"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Exceção de conversão de sinalk-> pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "recebido"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "falha ao enviar atualizações"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "falha ao analisar msg:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "sensor encontrado"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "dados desconhecidos analisados!"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"falha ao carregar a biblioteca científica, não é possível realizar a "
"atualização da calibração!"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Calibração incorreta do acelerômetro"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "distorções magnéticas"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Erro a carregar"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "falha ao carregar piloto"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Pilotos Disponíveis"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "aviso: falha ao abrir arquivo especial"

#: ../autopilot.py:157
msgid "for writing"
msgstr "para escrever"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "não pode acariciar o cão de guarda"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr "aviso: falha ao tornar o processo do piloto automático em tempo real"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "servidor / cliente está funcionando muito _lentamente_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "os sensores estão funcionando muito devagar"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "a rotina do piloto automático está funcionando muito _lentamente_"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "servo está funcionando muito devagar"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "iteração do piloto automático está muito lenta"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "AVISO: executando o piloto automático como root!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "inicialização completa"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Biblioteca RTIMU não detectada, instale-a"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Usando o arquivo de configurações"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "ERROR: No IMU Detected"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "ERROR: IMU Init Failed, nenhum dado inercial disponível"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "aviso, falha ao tornar o processo imu em tempo real"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "feito processo de imu em tempo real"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "definindo a polarização inicial do giroscópio"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "processo imu falhou em manter o tempo"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "falhou ao ler IMU!"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "taxa imu definida para taxa"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "polarização giroscópica muito alta, redefinindo sensores"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "bússola fora de alcance, reiniciando"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "aviso, falhou ao fazer o processo de calibração outro"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"aviso, falha ao tornar o processo de calibração ocioso, tentando renice"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "aviso, falha ao renice o processo de calibração"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "calibração carregada, começando"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "Falha na importação de ajuste de calibração"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "valores de aceleração inválidos"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "estouro no soquete udp pypilot"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "estouro no soquete pypilot"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "falha ao enviar pacote udp"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "O soquete do pypilot falhou ao enviar para"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "socket send demorou muito!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "socket send error"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "exceção de soquete pypilot"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"caindo de volta para o soquete não bloqueador python, consumirá mais cpu"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "socket send error in server flush"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "erro ao receber dados"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "erro de leitura"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "encontrou mais dispositivos por caminho"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "removendo dispositivo GPS"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr ""
"nenhum módulo pyudev! fará a varredura de dispositivos usb com freqüência!"

#: ../serialprobe.py:359
msgid "success"
msgstr "sucesso"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "falhou ao gravar o dispositivo"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "aviso, registrando valor existente:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "falha ao ler o arquivo de configuração:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "falha ao gravar o arquivo de configuração:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Arquivo de configuração de gravação de exceção:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "não é possível detectar automaticamente o servidor pypilot"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "mensagem inválida do servidor:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "aviso, o cliente pypilot já tem conexão"

#: ../client.py:363
msgid "connect failed to"
msgstr "conexão falhou a"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "Falha ao conectar a"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "nenhum servidor pypilot encontrado"

#: ../client.py:522
msgid "usage"
msgstr "uso"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "definir o host ou endereço IP"

#: ../client.py:526
msgid "print info about each value type"
msgstr "imprimir informações sobre cada tipo de valor"

#: ../client.py:527
msgid "continuous watch"
msgstr "relógio contínuo"

#: ../client.py:528
msgid "show this message"
msgstr "mostre esta mensagem"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "Falha ao recuperar a lista de valores!"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "recuperação de tempo limite"

#: ../client.py:569
msgid "missing"
msgstr "ausente"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "valor inicial inválido para propriedade de intervalo"

#: ../values.py:184
msgid "invalid set"
msgstr "conjunto inválido"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "gpsd conectado"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd falhou ao conectar"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "exceção conectando ao GPS"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd desconectado"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "sucesso PROBE do gpsd"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "A sonda gpsd falhou"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd desativado"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd falhou ao determinar a taxa de transmissão serial do dispositivo"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "tempo limite do gpsd por falta de dados"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd recebeu mensagem inválida"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd obteve sinalizador para tubo:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "sonda serial gpsd"

#~ msgid "exception in calibration:"
#~ msgstr "exceção na calibração:"

#~ msgid "warning: unhandled message"
#~ msgstr "aviso: mensagem não tratada"

#~ msgid "Autopilot Control"
#~ msgstr "Controle do piloto automático"

#~ msgid "AP"
#~ msgstr "Vocês"

#~ msgid "N/A"
#~ msgstr "N / D"

#~ msgid "        N/A        "
#~ msgstr "N / D"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "N / D"

#~ msgid "port"
#~ msgstr "porta"

#~ msgid "starboard"
#~ msgstr "estibordo"

#~ msgid "Pilot"
#~ msgstr "Piloto"

#~ msgid "Compass"
#~ msgstr "Bússola"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Vento"

#~ msgid "True Wind"
#~ msgstr "True Wind"

#~ msgid "Center"
#~ msgstr "Centro"

#~ msgid "&Scope"
#~ msgstr "&Alcance"

#~ msgid "&Client"
#~ msgstr "&Cliente"

#~ msgid "C&alibration"
#~ msgstr "C & calibração"

#~ msgid "Close"
#~ msgstr "Fechar"

#~ msgid "Calibration"
#~ msgstr "Calibration"

#~ msgid "Boat is level"
#~ msgstr "Barco está nivelado"

#~ msgid "Reset"
#~ msgstr "Redefinir"

#~ msgid "Alignment"
#~ msgstr "Alinhamento"

#~ msgid "Heading"
#~ msgstr "Cabeçalho"

#~ msgid "     N/A     "
#~ msgstr "N / D"

#~ msgid "Offset"
#~ msgstr "Desvio"

#~ msgid "Coords"
#~ msgstr "Coords"

#~ msgid "Sea"
#~ msgstr "Mar"

#~ msgid "Boat"
#~ msgstr "Barco"

#~ msgid "Scope"
#~ msgstr "Alcance"

#~ msgid "Pitch"
#~ msgstr "Tom"

#~ msgid "Roll"
#~ msgstr "Lista"

#~ msgid "Heel"
#~ msgstr "Salto"

#~ msgid "alignment"
#~ msgstr "alinhamento"

#~ msgid "Calibration Age"
#~ msgstr "Idade de Calibração"

#~ msgid "Clear"
#~ msgstr "Claro"

#~ msgid "calibration locked"
#~ msgstr "calibração travada"

#~ msgid "accel"
#~ msgstr "acel"

#~ msgid "Sigma Points"
#~ msgstr "Pontos Sigma"

#~ msgid "local history"
#~ msgstr "história local"

#~ msgid "current"
#~ msgstr "atual"

#~ msgid "Calibration Points"
#~ msgstr "Pontos de Calibração"

#~ msgid "compass"
#~ msgstr "bússola"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Pressione cada botão quando o leme estiver na posição correta para calibrar."

#~ msgid "Rudder"
#~ msgstr "Leme"

#~ msgid "Reset Calibration"
#~ msgstr "Reiniciar calibração"

#~ msgid "Rudder Is Centered"
#~ msgstr "O leme está centrado"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "O leme está a estibordo"

#~ msgid "Scale"
#~ msgstr "Escala"

#~ msgid "Rudder is Port Range"
#~ msgstr "Leme é Port Range"

#~ msgid "Non Linearity"
#~ msgstr "Não-linearidade"

#~ msgid " range +-"
#~ msgstr "intervalo + -"

#~ msgid "degrees"
#~ msgstr "graus"

#~ msgid "rudder"
#~ msgstr "leme"

#~ msgid "settings"
#~ msgstr "definições"

#~ msgid "failed to load pywavefront:"
#~ msgstr "falha ao carregar pywavefront:"

#~ msgid "invalid display dimensions"
#~ msgstr "dimensões de exibição inválidas"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Você adicionou o repositório pypilot_data?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "não encontrado, bússola de textura não pode ser usada"

#~ msgid "Refresh"
#~ msgstr "Atualizar"

#~ msgid "Connected"
#~ msgstr "Conectado"

#~ msgid "Disconnected"
#~ msgstr "Desconectado"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "aviso, valor de escolha inválido especificado"

#~ msgid "pypilot Scope"
#~ msgstr "escopo pypilot"

#~ msgid "Zero"
#~ msgstr "Zero"

#~ msgid "Scale +"
#~ msgstr "Escala +"

#~ msgid "Scale -"
#~ msgstr "Escala -"

#~ msgid "Offset /\\"
#~ msgstr "Desvio /\\"

#~ msgid "Offset \\/"
#~ msgstr "Desvio \\/"

#~ msgid "Freeze"
#~ msgstr "Congelar"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Tempo"

#~ msgid "values not found:"
#~ msgstr "valores não encontrados:"
