# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "mal calibrat del timó"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "mal calibrat del servo timó"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "ha fallat l’autogain del servo timó"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot no ha pogut importar els mòduls necessaris. Heu oblidat d’executar "
"sudo python3 setup.py install?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ADVERTÈNCIA: la biblioteca Python ujson ha fallat, l'anàlisi consumirà més "
"CPU"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "el calibratge del servo no és vàlid"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "no s'ha pogut obrir el servo a:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "no s'ha pogut bloquejar / exclusiu"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "trobat"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "servo calibratge de càrrega"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "AVÍS: utilitzant el calibratge servo predeterminat !!"

#: ../servo.py:756
msgid "probing"
msgstr "sondatge"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "servo arduino detectat"

#: ../servo.py:781
msgid "device needed for option"
msgstr "dispositiu necessari per a l'opció"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea no ha pogut analitzar gps"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea no ha pogut analitzar el vent"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "excepció analitzant apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "anàlisi d'excepcions vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "cadena de canonades nmea sense manipular"

#: ../nmea.py:405
msgid "lost serial"
msgstr "sèrie perduda"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea té bandera per a la canonada de procés:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "hi accedeix un altre procés?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "es va esgotar el temps d'espera del dispositiu sèrie"

#: ../nmea.py:521
msgid "failed to open"
msgstr "no s'ha pogut obrir"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "servidor nmea al port"

#: ../nmea.py:587
msgid "bind failed."
msgstr "la connexió ha fallat."

#: ../nmea.py:589
msgid "listening on port"
msgstr "escoltant al port"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "per a connexions nmea"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "El servidor nmea té massa connexions"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "El client nmea ha perdut la connexió"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "nmea mitjó no en endolls!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea no ha pogut anul·lar el registre del sòcol"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea no ha pogut eliminar fd"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea no ha pogut eliminar l'adreça"

#: ../nmea.py:737
msgid "invalid value"
msgstr "valor no vàlid"

#: ../nmea.py:747
msgid "connect error"
msgstr "error de connexió"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "no s'ha pogut connectar"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "nmea client connectat"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "l'enquesta va trigar massa en el procés nmea."

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "nmea bridge ha perdut la connexió del servidor"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge va perdre la canonada al pilot automàtic"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge bandera d'enquesta no manipulada"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "bucle de procés nmea massa lent:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "bloc de canonades d'error a recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "no s'ha pogut recuperar la canonada sense bloqueig."

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "canonada plena"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "no es pot enviar"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "no s'ha pogut descodificar el sòcol de dades."

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "no s'ha pogut codificar el sòcol de dades."

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "no s'ha pogut escriure"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "ERROR no hi ha connexions al rellotge"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "elimina la connexió udp duplicada"

#: ../server.py:486
msgid "failed to monitor "
msgstr "no s'ha pogut controlar"

#: ../server.py:490
msgid "creating config directory: "
msgstr "creant directori de configuració:"

#: ../server.py:497
msgid "failed to load"
msgstr "no s'ha pogut carregar"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "les dades de còpia de seguretat també han fallat"

#: ../server.py:570
msgid "failed to write"
msgstr "no s'ha pogut escriure"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr ""
"pypilot_server: ha fallat la vinculació; ja esteu executant un servidor?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "la botiga persistent va trigar massa."

#: ../server.py:706
msgid "max connections reached"
msgstr "assolides les connexions màximes"

#: ../server.py:709
msgid "server add socket"
msgstr "servidor afegeix sòcol"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "canonada interna tancada, sortida del servidor"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "el sòcol del servidor està tancat de flush !!"

#: ../signalk.py:52
msgid "service removed"
msgstr "servei eliminat"

#: ../signalk.py:55
msgid "server lost"
msgstr "servidor perdut"

#: ../signalk.py:61
msgid "service add"
msgstr "afegir servei"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "fallat en"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "no és possible la detecció automàtica"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "provar"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "o bé"

#: ../signalk.py:138
msgid "read token"
msgstr "llegir el testimoni"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "no s'ha pogut llegir el testimoni"

#: ../signalk.py:171
msgid "probe"
msgstr "sonda"

#: ../signalk.py:175
msgid "could not"
msgstr "no podia"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "no s'ha pogut recuperar / analitzar les dades de"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "veure si el testimoni està a punt"

#: ../signalk.py:207
msgid "received token"
msgstr "testimoni rebut"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "no s'ha pogut emmagatzemar el testimoni"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "error en sol·licitar accés"

#: ../signalk.py:236
msgid "request access url"
msgstr "sol·licita URL d'accés"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "no es pot crear la connexió:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "mal estat, rebutjant el testimoni"

#: ../signalk.py:264
msgid "connection refused"
msgstr "connexió rebutjada"

#: ../signalk.py:313
msgid "server found"
msgstr "servidor trobat"

#: ../signalk.py:334
msgid "connected to"
msgstr "connectat a"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Excepció convertint signalk-> pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "rebut"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "no s'ha pogut enviar actualitzacions"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "no s'ha pogut analitzar msg:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "sensor trobat"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "dades desconegudes analitzades."

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"no s'ha pogut carregar la biblioteca científica, no es pot actualitzar el "
"calibratge."

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Calibració incorrecta de l'acceleròmetre"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "distorsions magnètiques"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "ERROR de càrrega"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "no s'ha pogut carregar el pilot"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Pilots disponibles"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "avís: no s'ha pogut obrir el fitxer especial"

#: ../autopilot.py:157
msgid "for writing"
msgstr "per escriure"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "no pot acariciar el gos de vigilància"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr "avís: no s'ha pogut fer el procés del pilot automàtic en temps real"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "el servidor / client s’executa massa lentament"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "els sensors funcionen massa lentament"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "la rutina del pilot automàtic s’executa massa lentament"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "el servo funciona massa lentament"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "la iteració del pilot automàtic funciona massa lenta"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "ADVERTIMENT: executant el pilot automàtic com a root!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "init completa"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "La biblioteca RTIMU no s'ha detectat. Instal·leu-la"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Utilitzant el fitxer de configuració"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "ERROR: no s'ha detectat cap IMU"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "ERROR: Error d’inici d’IMU, no hi ha dades inercials disponibles"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "advertiment, no s'ha pogut fer el procés imu en temps real"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "procés imu realitzat en temps real"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "s'estableix el biaix giroscòpic inicial"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "El procés imu no ha pogut mantenir el temps"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "no s'ha pogut llegir l'IMU."

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "tarifa imu establerta a taxa"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "biaix giroscòpic d’alt standing, restabliment dels sensors"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "brúixola fora del rang, restabliment"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "avís, no s'ha pogut fer que el procés de calibratge sigui altre"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"avís, no s'ha pogut deixar el procés de calibratge inactiu, provant Renice"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "advertiment, no s'ha pogut renunciar al procés de calibratge"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "calibratge carregat, arrencada"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "no s'ha pogut ajustar el calibratge de la importació"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "els valors d'accel no són vàlids"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "desbordament al sòcol pypilot udp"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "desbordament al sòcol de pilots"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "no s'ha pogut enviar el paquet udp"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "el socket pypilot no s'ha pogut enviar a"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "l'enviament de sòcol ha trigat massa!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "error d'enviament de sòcol"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "excepció de sòcol pypilot"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "en tornar al sòcol no bloquejant Python, es consumirà més CPU"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "error d’enviament de sòcol a l’escomesa del servidor"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "error en rebre dades"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "error de lectura"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "s'han trobat més dispositius per ruta"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "eliminació del dispositiu GPS"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "cap mòdul pyudev! escanejarà dispositius USB sovint!"

#: ../serialprobe.py:359
msgid "success"
msgstr "èxit"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "no s'ha pogut gravar el dispositiu"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "advertiment, registrant el valor existent:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "no s'ha pogut llegir el fitxer de configuració:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "no s'ha pogut escriure el fitxer de configuració:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Excepció de l'escriptura del fitxer de configuració:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "la detecció automàtica del servidor pypilot no és possible"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "missatge no vàlid del servidor:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "avís, el client pypilot ja té connexió"

#: ../client.py:363
msgid "connect failed to"
msgstr "no s'ha pogut connectar"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "no s'ha pogut connectar a"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "no s'ha trobat cap servidor pypilot"

#: ../client.py:522
msgid "usage"
msgstr "ús"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "definiu l'adreça d'amfitrió o IP"

#: ../client.py:526
msgid "print info about each value type"
msgstr "imprimeix informació sobre cada tipus de valor"

#: ../client.py:527
msgid "continuous watch"
msgstr "rellotge continu"

#: ../client.py:528
msgid "show this message"
msgstr "mostra aquest missatge"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "no s'ha pogut recuperar la llista de valors."

#: ../client.py:566
msgid "timeout retrieving"
msgstr "recuperació del temps d'espera"

#: ../client.py:569
msgid "missing"
msgstr "desaparegut"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "valor inicial no vàlid per a la propietat de l'interval"

#: ../values.py:184
msgid "invalid set"
msgstr "conjunt no vàlid"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "GPS connectat"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd no s'ha pogut connectar"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "excepció que es connecta a GPS"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "GPS desconnectat"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "gpsd PROBE èxit"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "ha fallat la sonda gpsd"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd desactivat"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr ""
"gpsd no ha pogut determinar la velocitat de transmissió en sèrie del "
"dispositiu"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "temps d'espera gpsd per manca de dades"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd ha rebut un missatge no vàlid"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd té bandera per a canonada:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "sonda sèrie GPS"

#~ msgid "exception in calibration:"
#~ msgstr "excepció en el calibratge:"

#~ msgid "warning: unhandled message"
#~ msgstr "advertència: missatge no gestionat"

#~ msgid "Autopilot Control"
#~ msgstr "Control del pilot automàtic"

#~ msgid "AP"
#~ msgstr "Vostè"

#~ msgid "N/A"
#~ msgstr "N / A"

#~ msgid "        N/A        "
#~ msgstr "N / A"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "N / A"

#~ msgid "port"
#~ msgstr "port"

#~ msgid "starboard"
#~ msgstr "estribord"

#~ msgid "Pilot"
#~ msgstr "Pilot"

#~ msgid "Compass"
#~ msgstr "Brúixola"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Vent"

#~ msgid "True Wind"
#~ msgstr "Vent vertader"

#~ msgid "Center"
#~ msgstr "Centre"

#~ msgid "&Scope"
#~ msgstr "&Abast"

#~ msgid "&Client"
#~ msgstr "&Client"

#~ msgid "C&alibration"
#~ msgstr "Ca&libratge"

#~ msgid "Close"
#~ msgstr "Tanca"

#~ msgid "Calibration"
#~ msgstr "Calibratge"

#~ msgid "Boat is level"
#~ msgstr "El vaixell està a nivell"

#~ msgid "Reset"
#~ msgstr "Restableix"

#~ msgid "Alignment"
#~ msgstr "Alineació"

#~ msgid "Heading"
#~ msgstr "Encapçalament"

#~ msgid "     N/A     "
#~ msgstr "N / A"

#~ msgid "Offset"
#~ msgstr "Desplaçament"

#~ msgid "Coords"
#~ msgstr "coords"

#~ msgid "Sea"
#~ msgstr "Mar"

#~ msgid "Boat"
#~ msgstr "Vaixell"

#~ msgid "Scope"
#~ msgstr "Abast"

#~ msgid "Pitch"
#~ msgstr "Brea"

#~ msgid "Roll"
#~ msgstr "Rodar"

#~ msgid "Heel"
#~ msgstr "Taló"

#~ msgid "alignment"
#~ msgstr "alineació"

#~ msgid "Calibration Age"
#~ msgstr "Edat de calibració"

#~ msgid "Clear"
#~ msgstr "Clar"

#~ msgid "calibration locked"
#~ msgstr "calibratge bloquejat"

#~ msgid "accel"
#~ msgstr "accel"

#~ msgid "Sigma Points"
#~ msgstr "Punts Sigma"

#~ msgid "local history"
#~ msgstr "història local"

#~ msgid "current"
#~ msgstr "actual"

#~ msgid "Calibration Points"
#~ msgstr "Punts de calibració"

#~ msgid "compass"
#~ msgstr "brúixola"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Premeu cada botó quan el timó estigui a la posició correcta per calibrar."

#~ msgid "Rudder"
#~ msgstr "Timó"

#~ msgid "Reset Calibration"
#~ msgstr "Restableix la calibració"

#~ msgid "Rudder Is Centered"
#~ msgstr "El timó està centrat"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "El timó és la gamma d’estribord"

#~ msgid "Scale"
#~ msgstr "Escala"

#~ msgid "Rudder is Port Range"
#~ msgstr "El timó és Port Range"

#~ msgid "Non Linearity"
#~ msgstr "No linealitat"

#~ msgid " range +-"
#~ msgstr "rang + -"

#~ msgid "degrees"
#~ msgstr "graus"

#~ msgid "rudder"
#~ msgstr "timó"

#~ msgid "settings"
#~ msgstr "configuració"

#~ msgid "failed to load pywavefront:"
#~ msgstr "no s'ha pogut carregar pywavefront:"

#~ msgid "invalid display dimensions"
#~ msgstr "dimensions de visualització no vàlides"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Heu afegit el dipòsit pypilot_data?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "no es troba, la brúixola de textura no es pot utilitzar"

#~ msgid "Refresh"
#~ msgstr "Actualització"

#~ msgid "Connected"
#~ msgstr "Connectat"

#~ msgid "Disconnected"
#~ msgstr "Desconnectat"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "advertiment, s'ha especificat un valor d'elecció no vàlid"

#~ msgid "pypilot Scope"
#~ msgstr "piràmot Abast"

#~ msgid "Zero"
#~ msgstr "Zero"

#~ msgid "Scale +"
#~ msgstr "Escala +"

#~ msgid "Scale -"
#~ msgstr "Escala -"

#~ msgid "Offset /\\"
#~ msgstr "Desplaçament / \\"

#~ msgid "Offset \\/"
#~ msgstr "Desplaçament \\ /"

#~ msgid "Freeze"
#~ msgstr "Congelar"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Temps"

#~ msgid "values not found:"
#~ msgstr "valors no trobats:"

#~ msgid "in"
#~ msgstr "dins"

#~ msgid "seconds"
#~ msgstr "segons"

#~ msgid "nmea client failed to connect to"
#~ msgstr "El client nmea no s'ha pogut connectar"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "no s'ha pogut crear el sòcol nmea com a host: port"

#~ msgid "terminate calibration process"
#~ msgstr "finalitzar el procés de calibratge"
