# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "huono peräsimen kalibrointi"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "huono servopyörän kalibrointi"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "servo-peräsimen automaattinen vahvistus epäonnistui"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot epäonnistui tarvittavien moduulien tuomisessa. Unohtuiko suorittaa "
"sudo python3 setup.py install?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"VAROITUS: python ujson -kirjasto epäonnistui, jäsentäminen kuluttaa enemmän "
"prosessoria"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "servokalibrointi on virheellinen"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "epäonnistui avaamasta servoa:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "epäonnistunut asetettu esto / yksinoikeus"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "löytyi"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "servokalibroinnin lataus"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "VAROITUS: oletus servokalibrointi !!"

#: ../servo.py:756
msgid "probing"
msgstr "koettelemalla"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "arduino-servo havaittu"

#: ../servo.py:781
msgid "device needed for option"
msgstr "tarvittava laite"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea ei pystynyt jäsentämään GPS: ää"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea ei pystynyt jäsentämään tuulta"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "poikkeus jäsentää apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "poikkeus jäsentää vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "käsittelemätön nmea-putkijono"

#: ../nmea.py:405
msgid "lost serial"
msgstr "kadonnut sarja"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea sai lipun prosessiputkelle:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "onko toinen prosessi pääsy siihen?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "sarjalaite aikakatkaistiin"

#: ../nmea.py:521
msgid "failed to open"
msgstr "epäonnistui avaaminen"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "nmea-palvelin portissa"

#: ../nmea.py:587
msgid "bind failed."
msgstr "sidonta epäonnistui."

#: ../nmea.py:589
msgid "listening on port"
msgstr "kuuntelee satamassa"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "nmea-yhteyksille"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "nmea-palvelimella on liian monta yhteyttä"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "nmea -asiakas katkaisi yhteyden"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "nmea-sukka ei ole pistorasioissa!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea ei onnistunut poistamaan pistorasian rekisteröintiä"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea ei onnistunut poistamaan fd: tä"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea ei onnistunut poistamaan osoitetta"

#: ../nmea.py:737
msgid "invalid value"
msgstr "Kelpaamaton arvo"

#: ../nmea.py:747
msgid "connect error"
msgstr "yhteysvirhe"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "ei voida yhdistää"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "nmea -asiakas yhdistetty"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "kysely kesti liian kauan nmea-prosessissa!"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "nmea-silta katosi palvelinyhteyden"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea-silta menetti putken autopilotille"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "nmea-silta käsittelemätön kyselylippu"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "nmea-prosessisilmukka liian hidas:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "virhe putkilohko recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "epäonnistui rekvisiittaista putkea!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "putki täynnä"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "ei voi lähettää"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "ei onnistunut purkamaan datapistoketta!"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "ei onnistunut koodaamaan datapistoketta!"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "epäonnistui kirjoittaminen"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "VIRHE ei yhteyttä kellossa"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "Poista päällekkäinen udp-yhteys"

#: ../server.py:486
msgid "failed to monitor "
msgstr "ei onnistunut valvomaan"

#: ../server.py:490
msgid "creating config directory: "
msgstr "määrityshakemiston luominen:"

#: ../server.py:497
msgid "failed to load"
msgstr "lataus epäonnistui"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "varmuuskopiointi epäonnistui"

#: ../server.py:570
msgid "failed to write"
msgstr "ei kirjoittanut"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: sidonta epäonnistui; jo palvelinta?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "jatkuva myymälä kesti liian kauan!"

#: ../server.py:706
msgid "max connections reached"
msgstr "maksimiliitännät saavutettu"

#: ../server.py:709
msgid "server add socket"
msgstr "palvelimen lisäyspistoke"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "sisäinen putki suljettu, palvelin poistuu"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "palvelinpistoke suljettu huuhtelusta!"

#: ../signalk.py:52
msgid "service removed"
msgstr "palvelu poistettu"

#: ../signalk.py:55
msgid "server lost"
msgstr "palvelin menetetty"

#: ../signalk.py:61
msgid "service add"
msgstr "palvelu lisää"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "epäonnistui"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "automaattinen tunnistus ei ole mahdollista"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "yrittää"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "tai"

#: ../signalk.py:138
msgid "read token"
msgstr "lukea tunnusta"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "tunnuksen lukeminen epäonnistui"

#: ../signalk.py:171
msgid "probe"
msgstr "koetin"

#: ../signalk.py:175
msgid "could not"
msgstr "ei pystynyt"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "epäonnistui tietojen noutamisesta / jäsentämisestä"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "katso onko tunniste valmis"

#: ../signalk.py:207
msgid "received token"
msgstr "saanut tunnuksen"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "tunnuksen tallentaminen epäonnistui"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "virhe pyydettäessä käyttöoikeutta"

#: ../signalk.py:236
msgid "request access url"
msgstr "pyydä käyttöoikeuden URL -osoitetta"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "ei voi luoda yhteyttä:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "huono tila, hylkää merkki"

#: ../signalk.py:264
msgid "connection refused"
msgstr "yhteys evätty"

#: ../signalk.py:313
msgid "server found"
msgstr "palvelin löydetty"

#: ../signalk.py:334
msgid "connected to"
msgstr "yhdistetty"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Poikkeus muuntaa opasteet-> pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "sai"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "päivitysten lähettäminen epäonnistui"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "viestin jäsennys epäonnistui:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "anturi löytyi"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "tuntemattomia tietoja on jäsennelty!"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"tieteellisen kirjaston lataaminen epäonnistui, kalibrointipäivitystä ei voi "
"suorittaa!"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Huono kiihtyvyysmittarin kalibrointi"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "magneettisia vääristymiä"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Virhe ladattaessa"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "epäonnistui lataamaan pilottia"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Saatavilla olevat lentäjät"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "varoitus: erikoistiedoston avaaminen epäonnistui"

#: ../autopilot.py:157
msgid "for writing"
msgstr "kirjoittamista varten"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "ei voi silittää vahtikoiraa"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"varoitus: autopilotin prosessin tekeminen reaaliaikaiseksi epäonnistui"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "palvelin / asiakas toimii liian _hitaasti_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "anturit käyvät liian hitaasti"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotin rutiini toimii liian hitaasti"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "servo toimii liian hitaasti"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "autopilotin iteraatio toimii liian hitaasti"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "VAROITUS: käytössä autopilotti root-käyttäjänä!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "init valmis"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-kirjastoa ei löydy, asenna se"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Asetustiedoston käyttäminen"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "VIRHE: IMU: ta ei havaittu"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "VIRHE: IMU Init epäonnistui, inertiatietoja ei ole käytettävissä"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "varoitus, epäonnistui imu-prosessin tekeminen reaaliajassa"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "teki imuprosessista reaaliaikaisen"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "alkuperäisen gyro-biasin asettaminen"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "imu-prosessi ei onnistunut pitämään aikaa"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "epäonnistui lukemaan IMU: ta!"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "imu-kurssi asetettu koroksi"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "liian korkea seisova gyro-bias, antureiden nollaaminen"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "kompassi kantaman ulkopuolella, nollaus"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "varoitus, kalibrointiprosessia ei tehty muuksi"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr "varoitus, kalibrointiprosessin siirtäminen lepotilaan epäonnistui"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "varoitus, kalibrointiprosessin muuttaminen epäonnistui"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "kalibrointi ladattu, alkaa"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "epäonnistunut tuontikalibrointisovellus"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "Accel-arvot ovat virheellisiä"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "ylivuoto pypilot udp -liitännässä"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "pypilot-pistorasian ylivuoto"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "udp-paketin lähettäminen epäonnistui"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "pypilot-pistorasian lähettäminen epäonnistui"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "liittimen lähettäminen kesti liian kauan!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "pistorasian lähetysvirhe"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "pypilot-pistorasian poikkeus"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"palatessasi pythonin estämättömään pistorasiaan, kuluttaa enemmän "
"prosessoria"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "pistorasian lähetysvirhe palvelimen huuhtelussa"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "virhe tietojen vastaanottamisessa"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "virhe luettaessa"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "löysi lisää laitteita polun mukaan"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "GPS-laitteen poistaminen"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "ei pyudev-moduulia! skannaa usb-laitteita usein!"

#: ../serialprobe.py:359
msgid "success"
msgstr "menestys"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "laitteen tallennus epäonnistui"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "varoitus, olemassa olevan arvon rekisteröinti:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "määritystiedoston lukeminen epäonnistui:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "määritystiedoston kirjoittaminen epäonnistui:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Poikkeuksen kirjoittava määritystiedosto:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "Pypilot-palvelimen automaattinen tunnistus ei ole mahdollista"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "virheellinen viesti palvelimelta:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "varoitus, pypilot-asiakkaalla on jo yhteys"

#: ../client.py:363
msgid "connect failed to"
msgstr "yhteyden muodostaminen epäonnistui"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "yhteyden muodostaminen epäonnistui"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "pypilot-palvelinta ei löydy"

#: ../client.py:522
msgid "usage"
msgstr "käyttö"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "aseta isäntä- tai ip-osoite"

#: ../client.py:526
msgid "print info about each value type"
msgstr "tulosta tiedot jokaisesta arvotyypistä"

#: ../client.py:527
msgid "continuous watch"
msgstr "jatkuva katselu"

#: ../client.py:528
msgid "show this message"
msgstr "näytä tämä viesti"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "arvoluettelon noutaminen epäonnistui!"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "aikakatkaisun haku"

#: ../client.py:569
msgid "missing"
msgstr "puuttuu"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "alueen omaisuuden alkuarvo on virheellinen"

#: ../values.py:184
msgid "invalid set"
msgstr "virheellinen sarja"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "gpsd kytketty"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd-yhteyden muodostaminen epäonnistui"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "GPS: ään yhdistävä poikkeus"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd katkaistu"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "gpsd PROBE menestys"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "GPSD-koetin epäonnistui"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd deaktivoitu"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd ei onnistunut määrittämään laitteen sarjasiirtonopeutta"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "GPSD-aikakatkaisu tietojen puutteesta"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd vastaanotti virheellisen viestin"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd sai lipun putkelle:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "gpsd-sarjakoetin"

#~ msgid "exception in calibration:"
#~ msgstr "poikkeus kalibroinnissa:"

#~ msgid "warning: unhandled message"
#~ msgstr "varoitus: käsittelemätön viesti"

#~ msgid "Autopilot Control"
#~ msgstr "Autopilottiohjaus"

#~ msgid "AP"
#~ msgstr "Sinä"

#~ msgid "N/A"
#~ msgstr "N / A"

#~ msgid "        N/A        "
#~ msgstr "N / A"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "N / A"

#~ msgid "port"
#~ msgstr "satamaan"

#~ msgid "starboard"
#~ msgstr "oikealle"

#~ msgid "Pilot"
#~ msgstr "Lentäjä"

#~ msgid "Compass"
#~ msgstr "Kompassi"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Tuuli"

#~ msgid "True Wind"
#~ msgstr "Todellinen tuuli"

#~ msgid "Center"
#~ msgstr "Keskusta"

#~ msgid "&Scope"
#~ msgstr "&Laajuus"

#~ msgid "&Client"
#~ msgstr "&Asiakas"

#~ msgid "C&alibration"
#~ msgstr "&Kalibrointi"

#~ msgid "Close"
#~ msgstr "kiinni"

#~ msgid "Calibration"
#~ msgstr "Kalibrointi"

#~ msgid "Boat is level"
#~ msgstr "Vene on vaakasuorassa"

#~ msgid "Reset"
#~ msgstr "Nollaa"

#~ msgid "Alignment"
#~ msgstr "Kohdistus"

#~ msgid "Heading"
#~ msgstr "Otsikko"

#~ msgid "     N/A     "
#~ msgstr "N / A"

#~ msgid "Offset"
#~ msgstr "Offset"

#~ msgid "Coords"
#~ msgstr "Coords"

#~ msgid "Sea"
#~ msgstr "Meri"

#~ msgid "Boat"
#~ msgstr "Vene"

#~ msgid "Scope"
#~ msgstr "Soveltamisala"

#~ msgid "Pitch"
#~ msgstr "Piki"

#~ msgid "Roll"
#~ msgstr "Rullaa"

#~ msgid "Heel"
#~ msgstr "Kantapää"

#~ msgid "alignment"
#~ msgstr "kohdistus"

#~ msgid "Calibration Age"
#~ msgstr "Kalibrointiaika"

#~ msgid "Clear"
#~ msgstr "Asia selvä"

#~ msgid "calibration locked"
#~ msgstr "kalibrointi lukittu"

#~ msgid "accel"
#~ msgstr "Accel"

#~ msgid "Sigma Points"
#~ msgstr "Sigma-pisteet"

#~ msgid "local history"
#~ msgstr "paikallista historiaa"

#~ msgid "current"
#~ msgstr "nykyinen"

#~ msgid "Calibration Points"
#~ msgstr "Kalibrointipisteet"

#~ msgid "compass"
#~ msgstr "kompassi"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Paina kutakin painiketta, kun peräsin on oikeassa asennossa kalibrointia "
#~ "varten."

#~ msgid "Rudder"
#~ msgstr "Peräsin"

#~ msgid "Reset Calibration"
#~ msgstr "Nollaa kalibrointi"

#~ msgid "Rudder Is Centered"
#~ msgstr "Peräsin on keskitetty"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "Peräsin on oikeanpuoleinen alue"

#~ msgid "Scale"
#~ msgstr "Mittakaava"

#~ msgid "Rudder is Port Range"
#~ msgstr "Peräsin on Port Range"

#~ msgid "Non Linearity"
#~ msgstr "Epälineaarisuus"

#~ msgid " range +-"
#~ msgstr "alue + -"

#~ msgid "degrees"
#~ msgstr "astetta"

#~ msgid "rudder"
#~ msgstr "peräsin"

#~ msgid "settings"
#~ msgstr "asetukset"

#~ msgid "failed to load pywavefront:"
#~ msgstr "pywavefrontin lataaminen epäonnistui:"

#~ msgid "invalid display dimensions"
#~ msgstr "virheelliset näytön mitat"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Lisäsitkö pypilot_data-arkiston?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "ei löydy, tekstuurikompassia ei voida käyttää"

#~ msgid "Refresh"
#~ msgstr "virkistää"

#~ msgid "Connected"
#~ msgstr "Yhdistetty"

#~ msgid "Disconnected"
#~ msgstr "Yhteys katkaistu"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "varoitus, virheellinen valinnan arvo määritetty"

#~ msgid "pypilot Scope"
#~ msgstr "pypilot-soveltamisala"

#~ msgid "Zero"
#~ msgstr "Nolla"

#~ msgid "Scale +"
#~ msgstr "Skaalaa +"

#~ msgid "Scale -"
#~ msgstr "Asteikko -"

#~ msgid "Offset /\\"
#~ msgstr "Offset / \\"

#~ msgid "Offset \\/"
#~ msgstr "Siirtymä \\ /"

#~ msgid "Freeze"
#~ msgstr "Jäätykää"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Aika"

#~ msgid "values not found:"
#~ msgstr "arvoja ei löydy:"

#~ msgid "in"
#~ msgstr "sisään"

#~ msgid "seconds"
#~ msgstr "sekuntia"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-asiakas epäonnistui yhteyden muodostamiseen"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "ei luonut nmea-liitäntää isäntänä: portti"

#~ msgid "terminate calibration process"
#~ msgstr "lopeta kalibrointi"
